const jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "Google",
    appliedDate: "Oct 15, 2024",
    salary: "$90k - $120k",
    location: "Remote",
    status: "Interview",
    nextStep: "Technical interview on Nov 5th at 2pm",
    highlightColor: "yellow",
  },
  {
    id: 2,
    title: "React Developer",
    company: "Meta",
    appliedDate: "Sep 28, 2024",
    salary: "$110k - $140k",
    location: "Hybrid - SF",
    status: "Offer",
    nextStep: "Respond to offer by Nov 8th",
    highlightColor: "green",
  },
  {
    id: 3,
    title: "Full Stack Engineer",
    company: "Shopify",
    appliedDate: "Oct 28, 2024",
    salary: "$100k - $130k",
    location: "Remote",
    status: "Applied",
    nextStep: "Waiting for response",
    highlightColor: "blue",
  },
  {
    id: 4,
    title: "Software Engineer",
    company: "Stripe",
    appliedDate: "Oct 30, 2024",
    salary: "$110k - $140k",
    location: "Remote",
    status: "Applied",
    nextStep: "Application under review",
    highlightColor: "blue",
  },
  {
    id: 5,
    title: "Junior Developer",
    company: "Netflix",
    appliedDate: "Oct 18, 2024",
    salary: "$85k - $110k",
    location: "Hybrid - LA",
    status: "Interview",
    nextStep: "Phone screen on Nov 4th at 10am",
    highlightColor: "yellow",
  },
  {
    id: 6,
    title: "Web Developer",
    company: "Amazon",
    appliedDate: "Oct 10, 2024",
    salary: "$95k - $125k",
    location: "On-site - Seattle",
    status: "Rejected",
    nextStep: "Position filled internally",
    highlightColor: "red",
  },
];

export default jobs;